DROP TABLE IF EXISTS document;

CREATE TABLE document (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  uuid TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  process_stage CHAR(20) NOT NULL DEFAULT "NOT PROCESSED",
  process_status CHAR(20) NOT NULL DEFAULT "NOT PROCESSED",
  retried INTEGER NOT NULL DEFAULT 0,
  title TEXT,
  body TEXT,
  processed_body TEXT,
  file_name TEXT,
  filepath TEXT
);
